name:                Samsara
version:             1.0.0
github:              "fcarne/Samsara"
license:             BSD3
author:              "Federico Carne"
maintainer:          "example@example.com"
copyright:           "2022 Federico Carne"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fcarne/Samsara#readme>

dependencies:
- base >= 4.7 && < 5

#library:
#  source-dirs: src

executables:
  Samsara:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    # - Samsara
    - filepath

#tests:
#  Samsara-test:
#    main:                Spec.hs
#    source-dirs:         test
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - Samsara
